Class {
	#name : 'CPEventBasedGatewaySubscriptionState',
	#superclass : 'Object',
	#category : 'BVC-BPM-Execution',
	#package : 'BVC-BPM-Execution'
}

{ #category : 'testing' }
CPEventBasedGatewaySubscriptionState >> isWaiting [ ^ false ]
{ #category : 'testing' }
CPEventBasedGatewaySubscriptionState >> isTriggered [ ^ false ]
{ #category : 'testing' }
CPEventBasedGatewaySubscriptionState >> isWithdrawn [ ^ false ]
