Class {
	#name : 'CPAssignment',
	#superclass : 'CFIdentifiableObject',
	#instVars : [ 'fromExpression', 'toExpression' ],
	#category : 'BVC-BPM-BPMN',
	#package : 'BVC-BPM-BPMN'
}
{ #category : 'accessing' }
CPAssignment >> fromExpression [ ^ fromExpression ]
{ #category : 'accessing' }
CPAssignment >> fromExpression: anObject [ fromExpression := anObject ]
{ #category : 'accessing' }
CPAssignment >> toExpression [ ^ toExpression ]
{ #category : 'accessing' }
CPAssignment >> toExpression: anObject [ toExpression := anObject ]
